function writer = write_image()
    writer.accepts = @(item) isa(item, 'gadgetron.types.Image');
    writer.write = @write_image_header_and_data;
end

function write_image_header_and_data(socket, image)
    write(socket, gadgetron.Constants.IMAGE);
    write_header(socket, image.header, image.attribute_string);
    write_attribute_string(socket, image.attribute_string);
    write_data(socket, image.data);
end

function write_header(socket, header, attribute_string)

% Guarantee header vector elements are row vectors before concatenating
    byterow = @(item) typecast(item(:).','uint8');

    write(socket, [byterow(uint16(header.version)) ...
    byterow(uint16(header.data_type)) ...
    byterow(uint64(header.flags)) ...
    byterow(uint32(header.measurement_uid)) ...
    byterow(uint16(header.matrix_size)) ...
    byterow(single(header.field_of_view)) ...
    byterow(uint16(header.channels)) ...
    byterow(single(header.position)) ...
    byterow(single(header.read_dir)) ...
    byterow(single(header.phase_dir)) ...
    byterow(single(header.slice_dir)) ...
    byterow(single(header.patient_table_position)) ...
    byterow(uint16(header.average)) ...
    byterow(uint16(header.slice)) ...
    byterow(uint16(header.contrast)) ...
    byterow(uint16(header.phase)) ...
    byterow(uint16(header.repetition)) ...
    byterow(uint16(header.set)) ...
    byterow(uint32(header.acquisition_time_stamp)) ...
    byterow(uint32(header.physiology_time_stamp)) ...
    byterow(uint16(header.image_type)) ...
    byterow(uint16(header.image_index)) ...
    byterow(uint16(header.image_series_index)) ...
    byterow(int32(header.user_int)) ...
    byterow(single(header.user_float)) ...
    byterow(uint32(strlength(attribute_string)))]);
end

function write_attribute_string(socket, attribute_string)
    gadgetron.external.writers.write_string(socket, attribute_string, 'uint64');
end

function write_data(socket, data)

    if isreal(data)
        output = data;
    else
        output = zeros([2, size(data)], class(data));
        output(1, :, :, :, :) = real(data);
        output(2, :, :, :, :) = imag(data);
    end
    
    write(socket, reshape(output, 1, []));
end